### Get All Category
GET http://localhost:3000/api/categories?page=1&limit=10

### Get Category by ID
GET http://localhost:3000/api/categories/1

### Update Category
PUT http://localhost:3000/api/categories/2
Content-Type: application/json

{
    "name": "Updated Category",
    "description": "Updated Category"
}

### Create Category
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "name": "New Category",
    "description": "New Category"
}

### Delete Category
DELETE http://localhost:3000/api/categories/1

### Get All Product
GET http://localhost:3000/api/products?page=1&limit=10

### Get Product by ID
GET http://localhost:3000/api/products/1

### Update Product
PUT http://localhost:3000/api/products/2
Content-Type: application/json

{
    "name": "Updated Product",
    "description": "Updated Product Description",
    "price": 15000,
    "stock": 20,
    "category_id": 2
}

### Create Product
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name": "New Product",
    "description": "New Product Description",
    "price": 20000,
    "stock": 30,
    "category_id": 6
}

### Delete Product
DELETE http://localhost:3000/api/products/1
